[package]
name = "squashfs_rs"
version = "0.1.0"
authors = ["Zachary Dremann <dremann@gmail.com>"]
edition = "2018"

[dependencies]
positioned_io = { package = "positioned-io-preview", version = "0.3.3", path = "../positioned-io" }
packed_serialize = { path = "packed_serialize" }
repr = { path = "repr" }
byteorder = "1.3.1"
parking_lot = "0.9.0"
bitflags = "1.1.0"
chrono = "0.4.6"

[workspace]
